# __Author__: Khoi Van 2021

from json import load
import os
import sys

sys.path.append(os.path.realpath('src'))

import csv
from operator import itemgetter
from pathlib import Path
from typing import Dict, List, Set, Tuple

import pytest
from src.find_manuals import find_match, load_directory_file


CURRENT_FILEPATH = Path(__file__).resolve().parent.parent
DATA_FOLDER = CURRENT_FILEPATH.parent / 'src' / 'data'
INPUT_FOLDER = DATA_FOLDER / 'manuals'


@pytest.fixture
def directory() -> List[Dict[str, str]]:
    return load_directory_file()


@pytest.mark.parametrize(
    "item, expect", [
        ({'manufacturerSKU': 'VF2927L', 'brand': 'Dimplex'},                                # Dimplex
         'Dimplex/7213460100R05_EN.pdf'),
        ({'manufacturerSKU': 'RBF30WC', 'brand': 'Dimplex'},
         'Dimplex/Revillusion_Dimplex.pdf'),
        ({'manufacturerSKU': 'PF3033HG', 'brand': 'Dimplex'},
         'Dimplex/PF3033_Dimplex.pdf'),
        ({'manufacturerSKU': 'XLF50', 'brand': 'Dimplex'},
         'Dimplex/XLF100_Dimplex.pdf'),
        ({'manufacturerSKU': 'XLF60', 'brand': 'Dimplex'},
         'Dimplex/7215520100R00.pdf'),
        ({'manufacturerSKU': 'CDFI1000-PRO', 'brand': 'Dimplex'},
         'Dimplex/CDFI_Owners_Manual_7214300200R03.pdf'),
        ({'manufacturerSKU': 'GBF1500-PRO', 'brand': 'Dimplex'},
         'Dimplex/CDFI_Owners_Manual_7214300200R03.pdf'),
        ({'manufacturerSKU': 'GBF1000-PRO', 'brand': 'Dimplex'},
         'Dimplex/CDFI_Owners_Manual_7214300200R03.pdf'),
        ({'manufacturerSKU': 'VF2927L', 'brand': 'Dimplex'},
         'Dimplex/7213460100R05_EN.pdf'),
        ({'manufacturerSKU': 'BLF3451', 'brand': 'Dimplex'},
         'Dimplex/7213990100R02_EN.pdf'),
        ({'manufacturerSKU': 'BLF5051', 'brand': 'Dimplex'},
         'Dimplex/BLF5051.pdf'),
        ({'manufacturerSKU': 'BLF7451', 'brand': 'Dimplex'},
         'Dimplex/7214000100R01_EN.pdf'),
        ({'manufacturerSKU': 'BLF50', 'brand': 'Dimplex'},
         'Dimplex/7210380100R05_EN.pdf'),
        ({'manufacturerSKU': '4PVP-24SS', 'brand': 'DuraVent',                              # DuraVent
          'c__series': 'PelletVent Pro'},
         'DuraVent/duraVentPelletVentPro.pdf'),
        ({'manufacturerSKU': '46DVA-17TA', 'brand': 'DuraVent',
          'c__series': 'DirectVent Pro'},
         'DuraVent/duraVentDirectPro.pdf'),
        ({'manufacturerSKU': '46DVA-H2-SNK36', 'brand': 'DuraVent',
          'c__series': 'DirectVent Pro'},
         'DuraVent/duraVentDirectPro.pdf'),
        ({'manufacturerSKU': '46DVA-H2', 'brand': 'DuraVent',
          'c__series': 'DirectVent Pro'},
         'DuraVent/duraVentDirectPro.pdf'),
        ({'manufacturerSKU': '3DFA-25', 'brand': 'DuraVent',
          'c__series': 'DuraFlex Aluminum'},
         'DuraVent/duraVentDuraFlexAluminum.pdf'),
        ({'manufacturerSKU': 'VFSL30FP7010N', 'brand': 'Empire'},                             # Empire
         'Empire/VFSL30FP-Boulevard-SL-VF-Linear-Fireplace.pdf'),
        ({'manufacturerSKU': 'DVLL41FP92N', 'brand': 'Empire'},
         'Empire/DVLL41FP-Boulevard-Direct-Vent-Linear-Contemporary-Fireplace.pdf'),
        ({'manufacturerSKU': 'LS48THF', 'brand': 'Empire',
          'c__productCategory': 'Media Kits'},
         'ignore'),
        ({'manufacturerSKU': 'LS60THF', 'brand': 'Empire',
          'c__productCategory': 'Media Kits'},
         'ignore'),
        # ({'manufacturerSKU': 'OLL48SP12SN', 'brand': 'Empire'},
        #  'Empire/.pdf'),
        # ({'manufacturerSKU': 'OL48TP10N', 'brand': 'Empire'},
        #  'Empire/.pdf'),
        # ({'manufacturerSKU': 'OLL60SP12SN', 'brand': 'Empire'},
        #  'Empire/.pdf'),
        # ({'manufacturerSKU': 'OL60TP10N', 'brand': 'Empire'},
        #  'Empire/.pdf'),
        # ({'manufacturerSKU': 'ONR24N', 'brand': 'Empire'},
        #  'Empire/.pdf'),
        # ({'manufacturerSKU': 'OLI24N', 'brand': 'Empire'},
        #  'Empire/.pdf'),
        # ({'manufacturerSKU': 'OP36FP32MN', 'brand': 'Empire'},
        #  'Empire/.pdf'),
        # ({'manufacturerSKU': 'OP42FP32MN', 'brand': 'Empire'},
        #  'Empire/.pdf'),
        # ({'manufacturerSKU': 'DVP20CC30FN', 'brand': 'Empire'},
        #  'Empire/.pdf'),
        # ({'manufacturerSKU': 'VFD10CC30FN', 'brand': 'Empire'},
        #  'Empire/.pdf'),
        ({'manufacturerSKU': 'DVC26IN31N', 'brand': 'Empire'},
         'Empire/DVC202628IN37-1.pdf'),
        ({'manufacturerSKU': 'DVTL27FP90N', 'brand': 'Empire'},
         'Empire/DVTL27FP-Forest-Hills-Portrait-Traditional-Fireplace.pdf'),
        ({'manufacturerSKU': 'VFPC28IN33N', 'brand': 'Empire'},
         'Empire/VFPC2028IN3373NP-1.pdf'),
        ({'manufacturerSKU': 'DVL33FP32N', 'brand': 'Empire'},
         'Empire/DVL25FP-Loft-DV-Fireplace.pdf'),
        ({'manufacturerSKU': 'DVL33IN32N', 'brand': 'Empire'},
         'Empire/DVL2533IN.pdf'),
        ({'manufacturerSKU': 'VFLC28IN32N', 'brand': 'Empire'},
         'Empire/VFLC102028IN3272NP-1.pdf'),
        ({'manufacturerSKU': 'DVL25FP32N', 'brand': 'Empire'},
         'Empire/DVL25FP-Loft-DV-Fireplace.pdf'),
        ({'manufacturerSKU': 'DVL25IN33N', 'brand': 'Empire'},
         'Empire/DVL2533IN.pdf'),
        ({'manufacturerSKU': 'DVCT35CBN95N', 'brand': 'Empire'},
         'Empire/DVCT3035CBN-1.pdf'),
        ({'manufacturerSKU': 'DVCT36CBP95N', 'brand': 'Empire'},
         'Empire/DVCT3640CBP95-Homeowner.pdf'),
        ({'manufacturerSKU': 'DVCT40CSP95N', 'brand': 'Empire'},
         'Empire/DVCT40CSP95NP-1-Installer 40651-3-0520.pdf'),
        ({'manufacturerSKU': 'DVCD42FP30N', 'brand': 'Empire'},
         'Empire/DVCD323642FP3701NP-4-Homeowners.pdf'),
        ({'manufacturerSKU': 'DVX42FP31LN', 'brand': 'Empire'},
         'Empire/DVX3642FP3579 (2).pdf'),
        ({'manufacturerSKU': 'DVP36PP32EN', 'brand': 'Empire'},
         'Empire/DVP36PPSPENP-3.pdf'),
        ({'manufacturerSKU': 'VFD26FP20LN', 'brand': 'Empire'},
         'Empire/VFD26FP237.pdf'),
        ({'manufacturerSKU': 'VFPA32BP30LN', 'brand': 'Empire'},
         'Empire/VFPA32  VFPA36 39025-2-0620-VFPA3236BP3701LNP-2-Installer.pdf'),
        ({'manufacturerSKU': 'VFP36BP20LN', 'brand': 'Empire'},
         'Empire/VFP32BP-Vail-Premium-1.pdf'),
        ({'manufacturerSKU': 'CFL-24NG-C', 'brand': 'Majestic'},                             # Majestic
         'Majestic/CFL-18-C,24-C, 30-C_owners-manual.pdf'),
        ({'manufacturerSKU': 'BE36', 'brand': 'Majestic'},
         'Majestic/BE36,42 - ROYALTON - INSTALLATION.pdf'),
        ({'manufacturerSKU': 'LOGS-DRTWOOD-60', 'brand': 'Majestic',                         # item to ignore
          'c__productCategory': 'Media Kits'},
         'ignore'),
        ({'manufacturerSKU': 'SDLOGS-ODCOUG', 'brand': 'Majestic',
          'c__productCategory': 'Media Kits'},
         'ignore'),
        ({'manufacturerSKU': 'HDLOGS-ODCOUG', 'brand': 'Majestic',
          'c__productCategory': 'Media Kits'},
         'ignore'),
        ({'manufacturerSKU': 'DRTWOOD-JADE', 'brand': 'Majestic',
          'c__productCategory': 'Media Kits'},
         'ignore'),
        ({'manufacturerSKU': 'ODGSR42ARN', 'brand': 'Majestic'},
         'Majestic/MAJESTIC_AL_FRESCO_INSTALLATION_MANUAL.pdf'),
        ({'manufacturerSKU': 'ASH50', 'brand': 'Majestic'},
         'Majestic/ASH50 - ASHLAND - INSTALLATION.pdf'),
        ({'manufacturerSKU': 'SB80', 'brand': 'Majestic'},
         'Majestic/SB60,80 HB - BILTMORE - INSTALLATION.pdf'),
        ({'manufacturerSKU': 'SB100', 'brand': 'Majestic'},
         'Majestic/SB100 - BILTMORE - INSTALLATION.pdf'),
        ({'manufacturerSKU': 'RCOR-DV36IN', 'brand': 'Majestic'},
         'Majestic/LCOR,RCOR-DV36IN - INSTALLATION.pdf'),
        ({'manufacturerSKU': 'ODCOUG-36', 'brand': 'Majestic'},
         'Majestic/COURTYARD_OD_36-42_INSTALL_4608-901.pdf'),
        ({'manufacturerSKU': 'ODCOUG-42', 'brand': 'Majestic'},
         'Majestic/COURTYARD_OD_36-42_INSTALL_4608-901.pdf'),
        ({'manufacturerSKU': 'VDY24/18D3R', 'brand': 'Majestic'},
         'Majestic/VDY18,24,30 - DUZY.pdf'),
        ({'manufacturerSKU': 'ECHEL48STIN-C', 'brand': 'Majestic'},
         'Majestic/ECHEL36,48,60,72 - IN,STIN - ECHELON II - INSTALLATION.pdf'),
        ({'manufacturerSKU': 'ODFORTG-36', 'brand': 'Majestic'},
         'Majestic/FORTRESS_ODFORTG-36_Install_4602-901.pdf'),
        ({'manufacturerSKU': 'JADE42IN-B', 'brand': 'Majestic'},
         'Majestic/JADE32IN-B, JADE42IN-B INSTALLATION.pdf'),
        ({'manufacturerSKU': 'ODLANAIG-51', 'brand': 'Majestic'},
         'Majestic/Lanai_ODLANAIG-51-Install_20308571.pdf'),
        ({'manufacturerSKU': 'MONTANA-36', 'brand': 'Majestic'},
         'Majestic/montana36-42.pdf'),
        ({'manufacturerSKU': 'MONTANA-42', 'brand': 'Majestic'},
         'Majestic/montana36-42.pdf'),
        ({'manufacturerSKU': 'OXDV30SP', 'brand': 'Majestic'},
         'Majestic/Oxford OXDV-IPI.pdf'),
        ({'manufacturerSKU': 'OXDV30_IPI', 'brand': 'Majestic'},
         'Majestic/Oxford OXDV-IPI.pdf'),
        ({'manufacturerSKU': 'ODPALGST-48', 'brand': 'Majestic'},
         'Majestic/Palazzo_single_and_see_thru_installation_manual.pdf'),
        ({'manufacturerSKU': 'ODPLAZA-L24S', 'brand': 'Majestic'},
         'Majestic/ODPLAZA-L24S Linear Installation Manual 4079-311.pdf'),
        ({'manufacturerSKU': 'RBV4842IT', 'brand': 'Majestic'},
         'Majestic/RBV4236, RBV4842 - REVEAL B-VENT - INSTALLATION.pdf'),
        ({'manufacturerSKU': 'SA42C', 'brand': 'Majestic'},
         'Majestic/SA36C, SA42C - SOVERIGN - INSTALLATION.pdf'),
        ({'manufacturerSKU': 'TWILIGHT-II-C', 'brand': 'Majestic'},
         'Majestic/Twilight_II_installation_manual.pdf'),
        ({'manufacturerSKU': 'ODVILLAG-42T', 'brand': 'Majestic'},
         'Majestic/ODVILLAG-Villa-series.pdf'),
        ({'manufacturerSKU': 'ODVILLA-36T', 'brand': 'Majestic'},
         'Majestic/ODVILLA-Villawood-series.pdf'),

        ({'manufacturerSKU': 'AL144CLX2-G', 'brand': 'Modern Flames'},                      # Modern Flames
         'Modern Flames/Manual-AL-CLX-2.pdf'),
        ({'manufacturerSKU': 'FF43/BILV', 'brand': 'Modern Flames'},
         'Modern Flames/MODERN_FLAMES_BUILDER_INSTALLATION_MANUAL.pdf'),
        ({'manufacturerSKU': 'SF40/BILV', 'brand': 'Modern Flames'},
         'Modern Flames/MODERN_FLAMES_BUILDER_INSTALLATION_MANUAL.pdf'),
        ({'manufacturerSKU': 'HF42CBI', 'brand': 'Modern Flames'},
         'Modern Flames/Manual-Homefire_REV3.1_single.pdf'),
        ({'manufacturerSKU': 'LFV2-120/15-SH', 'brand': 'Modern Flames'},
         'Modern Flames/Manual-Landscape-GEN2-Rev2_singles.pdf'),
        ({'manufacturerSKU': 'LPM-4216', 'brand': 'Modern Flames'},
         'Modern Flames/MODERN_FLAMES_LANDSCAPE_PRO_2_INSTALLATION_MANUAL.pdf'),
        ({'manufacturerSKU': 'LPM-6616', 'brand': 'Modern Flames'},
         'Modern Flames/MODERN_FLAMES_LANDSCAPE_PRO_2_INSTALLATION_MANUAL.pdf'),
        ({'manufacturerSKU': 'LPM-7816', 'brand': 'Modern Flames'},
         'Modern Flames/MODERN_FLAMES_LANDSCAPE_PRO_2_INSTALLATION_MANUAL.pdf'),
        ({'manufacturerSKU': 'SC36-B', 'brand': 'Modern Flames'},
         'Modern Flames/Manual-Spectrum-REV2-single.pdf'),
        ({'manufacturerSKU': 'SCO-26EL', 'brand': 'Modern Flames'},
         'Modern Flames/Manual-Sunset-Charred-Oak-singles-rev-3.pdf'),
        ({'manufacturerSKU': 'ZCR2-29C', 'brand': 'Modern Flames'},
         'Modern Flames/Manual-ZCR-2_singles.pdf'),

        ({'manufacturerSKU': 'NBST27-F', 'brand': 'Monessen'},                             # Monessen
         'Monessen/NBST27 - NATURAL BLAZE SEE THRU.pdf'),
        ({'manufacturerSKU': 'VFF36LNI', 'brand': 'Monessen'},
         'Monessen/VFF Fireplace System - ARIA.pdf'),
        ({'manufacturerSKU': 'AVFL42NIP', 'brand': 'Monessen'},
         'Monessen/AVFL42NIP-PIP - 05.20.pdf'),
        ({'manufacturerSKU': 'AVFLST42NTSC', 'brand': 'Monessen'},
         'Monessen/AVFLST42NTSC.pdf'),
        ({'manufacturerSKU': 'AVFLST42NIP', 'brand': 'Monessen'},
         'Monessen/AVFL42STNIP-PIP - Install-Owner Manual_4118-900.pdf'),
        ({'manufacturerSKU': 'VFI33LNI', 'brand': 'Monessen'},
         'Monessen/VFI33 - SOLSTICE.pdf'),
        ({'manufacturerSKU': 'SD30NV', 'brand': 'Monessen'},
         'Monessen/SD30PV - SD30NV - SUNDANCE.pdf'),
        ({'manufacturerSKU': 'VFC24LNI', 'brand': 'Monessen'},
         'Monessen/VFC - SYMPHONY.pdf'),

        ({'manufacturerSKU': 'SF-BI30-EB', 'brand': 'SimpliFire'},                      # SimpliFire
         'SimpliFire/2040_980-SF-BI30-EB-SFBI36-EB-INSTALL.pdf'),
        ({'manufacturerSKU': 'SF-WMS38-BK', 'brand': 'SimpliFire'},
         'SimpliFire/2040_911.pdf'),
        ({'manufacturerSKU': 'SF-WM94-BK', 'brand': 'SimpliFire'},
         'SimpliFire/2040_903.pdf'),
        ({'manufacturerSKU': 'SF-ALL84-BK', 'brand': 'SimpliFire'},
         'SimpliFire/2040_981_ALLUSION_OWNER_INSTALL MANUAL.pdf'),
        ({'manufacturerSKU': 'SF-ALLP50-BK', 'brand': 'SimpliFire'},
         'SimpliFire/2044_980_ALLUSION_PLATINUM_OWNER_INTALL.pdf'),
        ({'manufacturerSKU': 'SF-INS30-BK', 'brand': 'SimpliFire'},
         'SimpliFire/2042-922_SF-SI4027_SF-SI4432_Installation.pdf'),
        ({'manufacturerSKU': 'SF-SC43-BK', 'brand': 'SimpliFire'},
         'SimpliFire/2041_980_ SCION_OWNER_INSTALL_MANUAL.pdf'),
        ({'manufacturerSKU': 'SF-SCT55-BK', 'brand': 'SimpliFire'},
         'SimpliFire/2043_980_SF-SCT43-55-BK_OWNER-INSTALL.pdf'),

        ({'manufacturerSKU': 'GX70NTE-1', 'brand': 'Napoleon'},                             # Napoleon
         'Napoleon/Ascent-X-70-Series-Manual.pdf'),
        ({'manufacturerSKU': 'B30NTRE-1', 'brand': 'Napoleon'},
         'Napoleon/Ascent--30-Manual.pdf'),
        ({'manufacturerSKU': 'ODLVF60ZEN', 'brand': 'Superior'},                            # Superior
         'Superior/Superior_VRE4600_Installation_manual_updated.pdf'),
        ({'manufacturerSKU': 'ODLVF48ZEN', 'brand': 'Superior'},
         'Superior/Superior_VRE4600_Installation_manual_updated.pdf'),
        ({'manufacturerSKU': 'DRL4060TEN', 'brand': 'Superior'},
         'Superior/DRL4060TEN DV FP Manual 900926-00.pdf'),
        ({'manufacturerSKU': 'DRL4060TEN-B', 'brand': 'Superior'},
         'Superior/901080-00_D_SUP_DRL4000_60-72-84_TEN-B_DV_FPs_SIT-PF1_IICO.pdf'),
        ({'manufacturerSKU': 'WRE3036WS', 'brand': 'Superior'},
         'Superior/SUPERIOR_WRE3036_INSTALLATION_MANUAL.pdf'),
        ({'manufacturerSKU': 'ERT3027', 'brand': 'Superior'},
         'Superior/ERT3027_Spark27_Electric_FP_IICO.pdf'),
        ({'manufacturerSKU': 'MPE-33-3', 'brand': 'Superior'},
         'Superior/900974-00_A_IHP_Capella33-36_ERT3033-36_MPE-33-36_IICO.pdf'),
        ({'manufacturerSKU': 'MPE-36-3', 'brand': 'Superior'},
         'Superior/900974-00_A_IHP_Capella33-36_ERT3033-36_MPE-33-36_IICO.pdf'),
        ({'manufacturerSKU': 'EPI22-1', 'brand': 'Timberwolf'},                            # Timberwolf
         'Timberwolf/W415-2799_EPI22-1 (CSA)_CeCf_05.07.21.pdf'),
        ({'manufacturerSKU': '2200-1', 'brand': 'Timberwolf'},
         'Timberwolf/2200-1-Installation-Manual-MAR20.pdf'),
        ({'manufacturerSKU': '2100-1', 'brand': 'Timberwolf'},
         'Timberwolf/2100-1-Manual.pdf'),
        ({'manufacturerSKU': 'TPI35', 'brand': 'Timberwolf'},
         'Timberwolf/W415-0865_TPSI35.pdf'),
        ({'manufacturerSKU': 'TPS35', 'brand': 'Timberwolf'},
         'Timberwolf/W415-0865_TPSI35.pdf'),
        ({'manufacturerSKU': 'TN20.INSB', 'brand': 'True North',                            # True North
          'c__series': 'TN20 Insert'},
         'True North/100000127-TN20B-INS-110618-28.pdf'),
        ({'manufacturerSKU': 'TN24.BODYA', 'brand': 'True North',
          'c__series': 'TN24'},
         'True North/100000458_True-North24-Installation-and-User-manual-090719-40.pdf'),
        ({'manufacturerSKU': 'TN20.LEGB', 'brand': 'True North',
          'c__series': 'TN20 Stove'},
         'True North/100000064_TN20-B_110618-28.pdf'),
        ({'manufacturerSKU': 'TN10.LEGA', 'brand': 'True North',
          'c__series': 'TN10'},
         'True North/TN10_Wood_Stove_Manual.pdf'),
    ]
)
def test_find_match(item: Dict[str, str], directory: List[Dict[str, str]],
                    expect: str):
    answer = find_match(item, directory)
    if expect is None or expect == 'ignore':
        assert answer == expect
    else:
        assert Path(answer.relative_to(INPUT_FOLDER)) == Path(expect)

